// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDAllianceWebSite.APIServer.Infrastructure;

namespace SDAllianceWebSite.APIServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210925032058_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            ConcurrencyStamp = "4eded47d-8e0e-44a8-9ccf-10921949681a",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e576",
                            ConcurrencyStamp = "f40919c6-24b1-42b4-a6ec-743ac87795d4",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e577",
                            ConcurrencyStamp = "cfdca168-e364-4b42-8620-73c536e09191",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e575"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e576"
                        },
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "a18be9c0-aa65-4af8-bd17-00bd9344e577"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CanComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayIntegral")
                        .HasColumnType("int");

                    b.Property<int>("DisplayLearningValue")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Institute")
                        .HasColumnType("longtext");

                    b.Property<int>("Integral")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassedVerification")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShowFavotites")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastOnlineTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LearningValue")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MBgImage")
                        .HasColumnType("longtext");

                    b.Property<string>("MainPageContext")
                        .HasMaxLength(20000000)
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long>("OnlineTime")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonalSignature")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("QQ")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SBgImage")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("SteamId")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentClass")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentId")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UnsealTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("WeChat")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            CanComment = true,
                            ConcurrencyStamp = "3a688f41-0f69-4ed6-bbcf-01a1e7052ce9",
                            DisplayIntegral = 0,
                            DisplayLearningValue = 0,
                            Email = "1278490989@qq.com",
                            EmailConfirmed = true,
                            Integral = 0,
                            IsPassedVerification = false,
                            IsShowFavotites = false,
                            LastOnlineTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LearningValue = 0,
                            LockoutEnabled = false,
                            MainPageContext = "### 这个人太懒了，什么也没写额(～￣▽￣)～",
                            NormalizedEmail = "1278490989@qq.com",
                            NormalizedUserName = "ADMIN",
                            OnlineTime = 0L,
                            PasswordHash = "AQAAAAEAACcQAAAAEFkdb984XQD2r/irVAEcEuswXdz5L8baUZDG5UnTYlCSobyQcsK9oWT8j2K8X8Khsw==",
                            PersonalSignature = "这个人太懒了，什么也没写额(～￣▽￣)～",
                            PhoneNumberConfirmed = false,
                            RegistTime = new DateTime(2021, 9, 25, 11, 20, 57, 839, DateTimeKind.Unspecified).AddTicks(477),
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BackUpArchiveId")
                        .HasColumnType("bigint");

                    b.Property<string>("BackgroundPicture")
                        .HasColumnType("longtext");

                    b.Property<string>("BriefIntroduction")
                        .HasColumnType("longtext");

                    b.Property<bool>("CanComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastEditTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MainPage")
                        .HasMaxLength(10000000)
                        .HasColumnType("longtext");

                    b.Property<string>("MainPicture")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalAuthor")
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalLink")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("PubishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReaderCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RealNewsTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SmallBackgroundPicture")
                        .HasColumnType("longtext");

                    b.Property<int>("ThumbsUpCount")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ArticleRelevance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayValue")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Modifier")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleRelevance");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.BackUpArchive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLastFail")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastBackUpTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("LastTimeUsed")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .IsUnique();

                    b.ToTable("BackUpArchives");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.BackUpArchiveDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BackUpArchiveId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BackUpTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFail")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("TimeUsed")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("BackUpArchiveId");

                    b.ToTable("BackUpArchiveDetails");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carousels");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ParentCodeNavigationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(10000000)
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long?>("UserSpaceCommentManagerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentCodeNavigationId");

                    b.HasIndex("UserSpaceCommentManagerId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ErrorCount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ErrorCounts");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Examine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<string>("Context")
                        .HasMaxLength(4000000)
                        .HasColumnType("longtext");

                    b.Property<int>("ContributionValue")
                        .HasColumnType("int");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("PassedAdminName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PassedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("PrepositionExamineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CommentId");

                    b.ToTable("Examines");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FavoriteFolder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BriefIntroduction")
                        .HasColumnType("longtext");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MainImage")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("FavoriteFolders");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FavoriteObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FavoriteFolderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("FavoriteFolderId");

                    b.ToTable("FavoriteObjects");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FriendLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FriendLinks");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.HistoryUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LoginName")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("longtext");

                    b.Property<string>("UserIdentity")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HistoryUsers");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Loginkey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Loginkeys");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AdditionalInfor")
                        .HasColumnType("longtext");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Rank")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.SendCount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("IP")
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SendCounts");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.SignInDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("SignInDay");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ThirdPartyLoginInfor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UniqueId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ThirdPartyLoginInfors");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ThumbsUp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ThumbsUpTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ThumbsUps");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.TimedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EveryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExecuteType")
                        .HasColumnType("int");

                    b.Property<long>("IntervalTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsLastFail")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPause")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRuning")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastExecutedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Parameter")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TimedTasks");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.UserOnlineInfor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserOnlineInfors");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.UserSpaceCommentManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("UserSpaceCommentManagers");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.FileManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("FileManagers");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.TokenCustom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Num")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TokenCustoms");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.UserFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FileManagerId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha1")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileManagerId");

                    b.ToTable("UserFiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Article", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreateUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ArticleRelevance", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", null)
                        .WithMany("Relevances")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.BackUpArchive", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", "Article")
                        .WithOne("BackUpArchive")
                        .HasForeignKey("SDAllianceWebSite.Shared.Model.BackUpArchive", "ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.BackUpArchiveDetail", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.BackUpArchive", "BackUpArchive")
                        .WithMany("BackUpArchiveDetails")
                        .HasForeignKey("BackUpArchiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BackUpArchive");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Comment", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.Comment", "ParentCodeNavigation")
                        .WithMany("InverseParentCodeNavigation")
                        .HasForeignKey("ParentCodeNavigationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.UserSpaceCommentManager", "UserSpaceCommentManager")
                        .WithMany("Comments")
                        .HasForeignKey("UserSpaceCommentManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Article");

                    b.Navigation("ParentCodeNavigation");

                    b.Navigation("UserSpaceCommentManager");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Examine", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("Examines")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", "Article")
                        .WithMany("Examines")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Article");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FavoriteFolder", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("FavoriteFolders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FavoriteObject", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.FavoriteFolder", "FavoriteFolder")
                        .WithMany("FavoriteObjects")
                        .HasForeignKey("FavoriteFolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("FavoriteFolder");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Message", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("Messages")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.SignInDay", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("SignInDays")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ThirdPartyLoginInfor", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("ThirdPartyLoginInfors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ThumbsUp", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDAllianceWebSite.Shared.Model.Article", "Article")
                        .WithMany("ThumbsUps")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.UserOnlineInfor", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithMany("UserOnlineInfors")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.UserSpaceCommentManager", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithOne("UserSpaceCommentManager")
                        .HasForeignKey("SDAllianceWebSite.Shared.Model.UserSpaceCommentManager", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.FileManager", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Model.ApplicationUser", "ApplicationUser")
                        .WithOne("FileManager")
                        .HasForeignKey("SDAllianceWebSite.Shared.Models.FileManager", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.UserFile", b =>
                {
                    b.HasOne("SDAllianceWebSite.Shared.Models.FileManager", "FileManager")
                        .WithMany("UserFiles")
                        .HasForeignKey("FileManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FileManager");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.ApplicationUser", b =>
                {
                    b.Navigation("Examines");

                    b.Navigation("FavoriteFolders");

                    b.Navigation("FileManager");

                    b.Navigation("Messages");

                    b.Navigation("SignInDays");

                    b.Navigation("ThirdPartyLoginInfors");

                    b.Navigation("UserOnlineInfors");

                    b.Navigation("UserSpaceCommentManager");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Article", b =>
                {
                    b.Navigation("BackUpArchive");

                    b.Navigation("Examines");

                    b.Navigation("Relevances");

                    b.Navigation("ThumbsUps");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.BackUpArchive", b =>
                {
                    b.Navigation("BackUpArchiveDetails");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.Comment", b =>
                {
                    b.Navigation("InverseParentCodeNavigation");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.FavoriteFolder", b =>
                {
                    b.Navigation("FavoriteObjects");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Model.UserSpaceCommentManager", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SDAllianceWebSite.Shared.Models.FileManager", b =>
                {
                    b.Navigation("UserFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
